name: Angular Deploy

# {1}
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to production"