name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
  # workflow_dispatch:
    

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Install dependencies
        run: npm ci

      # {4}
      - name: Build
        run: npm run build