name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
    

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Install dependencies
        run: npm ci

      # {4}
      - name: Build
        run: npm run build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: contains(['refs/heads/dev', 'refs/heads/staging', 'refs/heads/prod'], github.ref)
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to production"